---
abstract: 'A Catalyst Plugin for Sitemaps up to 2.5 billion urls.'
author:
  - 'Derek J. Curtis C<< <djcurtis at summersetsoftware dot com>> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-BigSitemap
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.32
  Catalyst: 0
  Modern::Perl: 1.20121103
  Moose: 2.1005
  Path::Class: 0.32
  Try::Tiny: 0.18
  WWW::Sitemap::XML: 1.121160
  perl: 5.10.2
resources:
  license: http://dev.perl.org/licenses/
version: undef
